# The Node.js implementation dynamically generates service descriptors
# and client stub definitions at runtime. Thus no Makefile related actions
# are required...
.PHONY: install build clean cleanall

# See https://grpc.io/docs/quickstart/go.html.
install:
	npm install

build:

clean:
	rm -fr ./node_modules

cleanall: