# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: kv.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='kv.proto',
  package='kv',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\x08kv.proto\x12\x02kv\"\x15\n\x06GetKey\x12\x0b\n\x03key\x18\x01 \x01(\t\"*\n\x08GetReply\x12\r\n\x05value\x18\x01 \x01(\t\x12\x0f\n\x07\x64\x65\x66ined\x18\x02 \x01(\x08\"7\n\x06SetKey\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t\x12\x11\n\tbroadcast\x18\x03 \x01(\x08\"\x19\n\x08SetReply\x12\r\n\x05value\x18\x01 \x01(\t\"\x06\n\x04Void\"\x10\n\x02IP\x12\n\n\x02ip\x18\x01 \x01(\t\"d\n\nStoreReply\x12(\n\x05store\x18\x01 \x03(\x0b\x32\x19.kv.StoreReply.StoreEntry\x1a,\n\nStoreEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t:\x02\x38\x01\x32\xa0\x01\n\x06\x43lient\x12!\n\x03Get\x12\n.kv.GetKey\x1a\x0c.kv.GetReply\"\x00\x12!\n\x03Set\x12\n.kv.SetKey\x1a\x0c.kv.SetReply\"\x00\x12\"\n\x04List\x12\x08.kv.Void\x1a\x0e.kv.StoreReply\"\x00\x12,\n\x10RegisterWithPeer\x12\x06.kv.IP\x1a\x0e.kv.StoreReply\"\x00\x62\x06proto3')
)




_GETKEY = _descriptor.Descriptor(
  name='GetKey',
  full_name='kv.GetKey',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='key', full_name='kv.GetKey.key', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=16,
  serialized_end=37,
)


_GETREPLY = _descriptor.Descriptor(
  name='GetReply',
  full_name='kv.GetReply',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='value', full_name='kv.GetReply.value', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='defined', full_name='kv.GetReply.defined', index=1,
      number=2, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=39,
  serialized_end=81,
)


_SETKEY = _descriptor.Descriptor(
  name='SetKey',
  full_name='kv.SetKey',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='key', full_name='kv.SetKey.key', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='value', full_name='kv.SetKey.value', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='broadcast', full_name='kv.SetKey.broadcast', index=2,
      number=3, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=83,
  serialized_end=138,
)


_SETREPLY = _descriptor.Descriptor(
  name='SetReply',
  full_name='kv.SetReply',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='value', full_name='kv.SetReply.value', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=140,
  serialized_end=165,
)


_VOID = _descriptor.Descriptor(
  name='Void',
  full_name='kv.Void',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=167,
  serialized_end=173,
)


_IP = _descriptor.Descriptor(
  name='IP',
  full_name='kv.IP',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='ip', full_name='kv.IP.ip', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=175,
  serialized_end=191,
)


_STOREREPLY_STOREENTRY = _descriptor.Descriptor(
  name='StoreEntry',
  full_name='kv.StoreReply.StoreEntry',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='key', full_name='kv.StoreReply.StoreEntry.key', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='value', full_name='kv.StoreReply.StoreEntry.value', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=_b('8\001'),
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=249,
  serialized_end=293,
)

_STOREREPLY = _descriptor.Descriptor(
  name='StoreReply',
  full_name='kv.StoreReply',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='store', full_name='kv.StoreReply.store', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[_STOREREPLY_STOREENTRY, ],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=193,
  serialized_end=293,
)

_STOREREPLY_STOREENTRY.containing_type = _STOREREPLY
_STOREREPLY.fields_by_name['store'].message_type = _STOREREPLY_STOREENTRY
DESCRIPTOR.message_types_by_name['GetKey'] = _GETKEY
DESCRIPTOR.message_types_by_name['GetReply'] = _GETREPLY
DESCRIPTOR.message_types_by_name['SetKey'] = _SETKEY
DESCRIPTOR.message_types_by_name['SetReply'] = _SETREPLY
DESCRIPTOR.message_types_by_name['Void'] = _VOID
DESCRIPTOR.message_types_by_name['IP'] = _IP
DESCRIPTOR.message_types_by_name['StoreReply'] = _STOREREPLY
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

GetKey = _reflection.GeneratedProtocolMessageType('GetKey', (_message.Message,), dict(
  DESCRIPTOR = _GETKEY,
  __module__ = 'kv_pb2'
  # @@protoc_insertion_point(class_scope:kv.GetKey)
  ))
_sym_db.RegisterMessage(GetKey)

GetReply = _reflection.GeneratedProtocolMessageType('GetReply', (_message.Message,), dict(
  DESCRIPTOR = _GETREPLY,
  __module__ = 'kv_pb2'
  # @@protoc_insertion_point(class_scope:kv.GetReply)
  ))
_sym_db.RegisterMessage(GetReply)

SetKey = _reflection.GeneratedProtocolMessageType('SetKey', (_message.Message,), dict(
  DESCRIPTOR = _SETKEY,
  __module__ = 'kv_pb2'
  # @@protoc_insertion_point(class_scope:kv.SetKey)
  ))
_sym_db.RegisterMessage(SetKey)

SetReply = _reflection.GeneratedProtocolMessageType('SetReply', (_message.Message,), dict(
  DESCRIPTOR = _SETREPLY,
  __module__ = 'kv_pb2'
  # @@protoc_insertion_point(class_scope:kv.SetReply)
  ))
_sym_db.RegisterMessage(SetReply)

Void = _reflection.GeneratedProtocolMessageType('Void', (_message.Message,), dict(
  DESCRIPTOR = _VOID,
  __module__ = 'kv_pb2'
  # @@protoc_insertion_point(class_scope:kv.Void)
  ))
_sym_db.RegisterMessage(Void)

IP = _reflection.GeneratedProtocolMessageType('IP', (_message.Message,), dict(
  DESCRIPTOR = _IP,
  __module__ = 'kv_pb2'
  # @@protoc_insertion_point(class_scope:kv.IP)
  ))
_sym_db.RegisterMessage(IP)

StoreReply = _reflection.GeneratedProtocolMessageType('StoreReply', (_message.Message,), dict(

  StoreEntry = _reflection.GeneratedProtocolMessageType('StoreEntry', (_message.Message,), dict(
    DESCRIPTOR = _STOREREPLY_STOREENTRY,
    __module__ = 'kv_pb2'
    # @@protoc_insertion_point(class_scope:kv.StoreReply.StoreEntry)
    ))
  ,
  DESCRIPTOR = _STOREREPLY,
  __module__ = 'kv_pb2'
  # @@protoc_insertion_point(class_scope:kv.StoreReply)
  ))
_sym_db.RegisterMessage(StoreReply)
_sym_db.RegisterMessage(StoreReply.StoreEntry)


_STOREREPLY_STOREENTRY._options = None

_CLIENT = _descriptor.ServiceDescriptor(
  name='Client',
  full_name='kv.Client',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=296,
  serialized_end=456,
  methods=[
  _descriptor.MethodDescriptor(
    name='Get',
    full_name='kv.Client.Get',
    index=0,
    containing_service=None,
    input_type=_GETKEY,
    output_type=_GETREPLY,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='Set',
    full_name='kv.Client.Set',
    index=1,
    containing_service=None,
    input_type=_SETKEY,
    output_type=_SETREPLY,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='List',
    full_name='kv.Client.List',
    index=2,
    containing_service=None,
    input_type=_VOID,
    output_type=_STOREREPLY,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='RegisterWithPeer',
    full_name='kv.Client.RegisterWithPeer',
    index=3,
    containing_service=None,
    input_type=_IP,
    output_type=_STOREREPLY,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_CLIENT)

DESCRIPTOR.services_by_name['Client'] = _CLIENT

# @@protoc_insertion_point(module_scope)
